# Generated by Django 4.2.3 on 2023-07-23 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=2)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=20, null=True, unique=True)),
                ('creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
